name: Deploy Story

on:
  push:
    branches:
    - master

jobs:
  storybook-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build-storybook
    - run: npm run deploy 
